#!/usr/bin/env bash
# Test: claudart/CLAUDE.md is a proper dev file, not a linked workspace artifact.
# Run from the claudart repo root.

PASS=0
FAIL=0
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLAUDE_MD="$REPO_ROOT/CLAUDE.md"
CLAUDE_DIR="$REPO_ROOT/.claude"

pass() { echo "  ✓ $1"; ((PASS++)); }
fail() { echo "  ✗ $1"; ((FAIL++)); }

echo ""
echo "claudart CLAUDE.md integrity check"
echo "==================================="

# 1. CLAUDE.md must exist
[ -e "$CLAUDE_MD" ] && pass "CLAUDE.md exists" || fail "CLAUDE.md missing"

# 2. CLAUDE.md must NOT be a symlink
[ ! -L "$CLAUDE_MD" ] && pass "CLAUDE.md is a real file (not symlink)" \
  || fail "CLAUDE.md is a symlink — claudart link was run here by mistake"

# 3. CLAUDE.md must not reference dc-flutter
if ! grep -q "dc-flutter" "$CLAUDE_MD" 2>/dev/null; then
  pass "CLAUDE.md has no dc-flutter references"
else
  fail "CLAUDE.md contains dc-flutter references"
fi

# 4. CLAUDE.md must not reference workspace paths
if ! grep -q "dev_tools/claude" "$CLAUDE_MD" 2>/dev/null; then
  pass "CLAUDE.md has no workspace path references"
else
  fail "CLAUDE.md contains workspace path references (dev_tools/claude)"
fi

# 5. CLAUDE.md must not carry the 'Generated by claudart link' header
if ! grep -q "Generated by claudart link" "$CLAUDE_MD" 2>/dev/null; then
  pass "CLAUDE.md is not a generated link artifact"
else
  fail "CLAUDE.md has 'Generated by claudart link' header"
fi

# 6. .claude must NOT be a symlink to the workspace
if [ ! -L "$CLAUDE_DIR" ]; then
  pass ".claude is not a symlink"
else
  fail ".claude is a symlink to the workspace — dc-flutter commands are bleeding in"
fi

# 7. CLAUDE.md must reference claudart's own SDK constraint
if grep -q ">=3.0.0" "$CLAUDE_MD" 2>/dev/null; then
  pass "CLAUDE.md references claudart SDK constraint (>=3.0.0)"
else
  fail "CLAUDE.md missing claudart SDK constraint"
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
echo ""
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
