// Generic starter content for workspace knowledge files.
// Updated by claudart teardown as sessions accumulate.

String dartTemplate(String dartVersion) => '''
# Generic Dart Practices
> Dart $dartVersion
> Updated by claudart teardown. Do not edit manually.

---

## Dart

- Prefer `const` constructors wherever possible
- Use `sealed` classes for exhaustive pattern matching over enums with behaviour
- Avoid `dynamic` — use generics or `Object?` with type checks
- Prefer named parameters for functions with more than two arguments
- Use `extension` types to wrap primitives with domain meaning
- `late` is a smell — prefer nullable or required initialisation

---

## Patterns to avoid

_Populated by teardown from real sessions._
''';

const String testingTemplate = '''
# Testing Patterns
> Updated by claudart teardown. Do not edit manually.

---

## Unit tests

- One assertion per test where possible — tests should have one reason to fail
- Name tests: `given_when_then` or plain English descriptions
- Mock at the boundary (repository level), not deep in the stack

## Coverage

- Coverage gaps must be justified, not silently ignored

---

## Patterns to avoid

_Populated by teardown from real sessions._
''';

String projectTemplate(String projectName) => '''
# Project: $projectName
> Updated by claudart teardown. Do not edit manually.

---

## Context

_Describe the project here. Updated as sessions accumulate._

---

## Architecture

_Key architectural decisions relevant to debugging._

---

## Hot paths

> Files confirmed useful across sessions. `↑` = confirmed once per session.

_Populated by teardown._

---

## Root cause patterns

> Patterns specific to this project.

_Populated by teardown._

---

## Anti-patterns

> Things that look relevant but aren\'t. Skip these first.

_Populated by teardown._
''';

String claudeMdTemplate({
  required String workspacePath,
  required String projectName,
  required List<String> genericFiles,
  String? sdkConstraint,
  String? flutterConstraint,
}) {
  final genericRefs = genericFiles
      .map((f) => '- $workspacePath/knowledge/generic/$f')
      .join('\n');

  final envLines = StringBuffer();
  if (sdkConstraint != null || flutterConstraint != null) {
    envLines.writeln('\n## Environment\n');
    if (sdkConstraint != null) envLines.writeln('- Dart SDK: `$sdkConstraint`');
    if (flutterConstraint != null) envLines.writeln('- Flutter: `$flutterConstraint`');
    envLines.writeln('\nDo not suggest APIs or syntax unavailable within these constraints.');
    envLines.writeln('\n---');
  }

  return '''
# CLAUDE.md
> Generated by claudart link | Project: $projectName
> Do not edit manually — re-run `claudart link` to regenerate.

## Workflow protocol

Always follow this order — no exceptions:
1. **Verify** — read the relevant files, understand current state
2. **Test** — run safely
3. **Confirm** — present result, wait for user confirmation
4. **Commit** — only after confirmed

Never commit before testing. Never skip confirmation.

---
${envLines}
## Knowledge base

Read the following files at the start of every session before doing anything else.

### Generic practices
$genericRefs

### Project context
- $workspacePath/knowledge/projects/$projectName.md

### Session state
- $workspacePath/handoff.md
- $workspacePath/skills.md

---

## Git rules

- **Never push to remote** under any circumstances
- Local commits only, and only when explicitly requested
''';
}
