import 'dart:convert';
import 'package:path/path.dart' as p;
import '../file_io.dart';
import '../paths.dart';
import '../sensitivity/token_map.dart';

/// Generates a human-readable token_map.md from token_map.json on demand.
/// [workspacePath] routes token_map.json to the per-project workspace.
void runMap({FileIO? io, String? workspacePath}) {
  final fileIO = io ?? const RealFileIO();

  final tokenMapPath = workspacePath != null
      ? tokenMapPathFor(workspacePath)
      : p.join(claudeDir, 'token_map.json');
  final tokenMapMdPath = workspacePath != null
      ? p.join(workspacePath, 'token_map.md')
      : p.join(claudeDir, 'token_map.md');

  final raw = fileIO.read(tokenMapPath);
  if (raw.isEmpty) {
    print('\n✗ No token map found at $tokenMapPath');
    print('  Run `claudart scan` first to build the token map.\n');
    return;
  }

  Map<String, dynamic> allTokens;
  try {
    allTokens = jsonDecode(raw) as Map<String, dynamic>;
  } catch (_) {
    print('\n✗ token_map.json is malformed.\n');
    return;
  }

  final tokenMap = TokenMap.load(tokenMapPath, io: fileIO);

  final buf = StringBuffer();
  buf.writeln('# Token Map');
  buf.writeln();
  buf.writeln('> Generated by `claudart map` — do not edit manually.');
  buf.writeln();
  buf.writeln('| Token | Real Name | Type | Extra |');
  buf.writeln('|-------|-----------|------|-------|');

  var activeCount = 0;
  for (final entry in allTokens.entries) {
    final token = entry.key;
    final meta = Map<String, dynamic>.from(entry.value as Map);
    final realName = meta['r'] as String? ?? '?';
    final deprecated = meta['deprecated'] as bool? ?? false;
    final colon = token.indexOf(':');
    final typePrefix = colon >= 0 ? token.substring(0, colon) : token;
    final extra = _formatExtra(meta);
    final depMark = deprecated ? ' ~~deprecated~~' : '';
    buf.writeln('| `$token` | $realName$depMark | $typePrefix | $extra |');
    if (!deprecated) activeCount++;
  }

  buf.writeln();
  buf.writeln('**Total:** ${allTokens.length} tokens '
      '($activeCount active)');

  fileIO.write(tokenMapMdPath, buf.toString());
  print('\n✓ Token map written to $tokenMapMdPath');
  print('  ${allTokens.length} tokens (${tokenMap.size} active)\n');
}

String _formatExtra(Map<String, dynamic> meta) {
  final parts = <String>[];
  if (meta.containsKey('deps')) parts.add('deps: ${meta['deps']}');
  if (meta.containsKey('kind')) parts.add('kind: ${meta['kind']}');
  if (meta.containsKey('on')) parts.add('on: ${meta['on']}');
  if (meta.containsKey('returns')) parts.add('returns: ${meta['returns']}');
  if (meta.containsKey('renamedTo')) parts.add('→ ${meta['renamedTo']}');
  return parts.isEmpty ? '' : parts.join(', ');
}
